### ISSUE TITLE
Validation prior submission 

### ISSUE THREAD

**Issue by lazmo88** [zaus/f3i-phonenumber#1]
Is it possible to consider feature that adds custom validation hook to the form and blocks the form submission of number is not valid?

Also, where are the current validation results saved to?

**Comment by zaus** [comment]
That should be covered in the "main" plugin: https://github.com/zaus/forms-3rdparty-integration#how-do-i-conditionally-submit-if-field--

As the `...get_submission` hook used by this plugin is earlier than the `...use_submission` hook I'm talking about, you shouldn't need to do anything special beyond validating your particular input.
